server : 
  port : 9081
  session:
    timeout: 30
  contextPath : /springboot
spring :
  http:
    encoding:
      force : true
      charset: UTF-8
  mvc:
    view:
      prefix : /WEB-INF/jsp/
      suffix : .jsp
  datasource:
    url: jdbc:mysql://localhost:3306/db_shiro?characterEncoding=utf8&useSSL=true
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource  
    filters : stat  
    maxActive : 20  
    initialSiz e: 1  
    maxWait : 60000  
    minIdle : 1  
    timeBetweenEvictionRunsMillis : 60000  
    minEvictableIdleTimeMillis : 300000  
    validationQuery : select 'x'  
    testWhileIdle : true  
    testOnBorrow: false  
    testOnReturn: false  
    poolPreparedStatements: true  
    maxOpenPreparedStatements: 20 
mybatis:
  mapper-locations : classpath:META-INF/mapper/*.xml
  typeAliasesPackage : com.xxfy.demo.dao